services:
  dmi4er4-userbot:
    build: .
    platform: linux/amd64
    container_name: dmi4er4-userbot
    network_mode: host
    env_file:
      - .env.dmi4er4
    volumes:
      - ./data-dmi4er4:/data
    restart: unless-stopped

  taak-userbot:
    build: .
    platform: linux/amd64
    container_name: taak-userbot
    network_mode: host
    env_file:
      - .env.taak
    volumes:
      - ./data-taak:/data
    restart: unless-stopped

  charndv-userbot:
    build: .
    platform: linux/amd64
    container_name: charndv-userbot
    network_mode: host
    env_file:
      - .env.charndv
    volumes:
      - ./data-charndv:/data
    restart: unless-stopped
